// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOjYRIPYogjm7wR0nyoFb55XIY3f4WE8E',
    appId: '1:287529575278:android:1efee00fbd7472c5eed77f',
    messagingSenderId: '287529575278',
    projectId: 'codev-68a70',
    storageBucket: 'codev-68a70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF3a7AaP1P8gnKmbLNz2ZUFkmNYzFYKUI',
    appId: '1:287529575278:ios:a2ad2ff9556e00f6eed77f',
    messagingSenderId: '287529575278',
    projectId: 'codev-68a70',
    storageBucket: 'codev-68a70.appspot.com',
    androidClientId: '287529575278-1rjlpn6i9u3oc3shu6pt2hpkc8hp871l.apps.googleusercontent.com',
    iosClientId: '287529575278-7lqie9946k82mb55tifcjsrs1idvmq6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.codevx',
  );

}